# Generated by Django 3.2.13 on 2022-12-20 10:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('themes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='theme_likes',
            field=models.ManyToManyField(related_name='user_themes_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
