# Generated by Django 3.2.13 on 2023-01-02 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20221225_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='kakao_access_token',
            field=models.TextField(blank=True),
        ),
    ]
